WebApplication2/Controllers/AdblockController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class AdblockController : Controller
    {
        // GET: Adblock
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication2/Controllers/AdditionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class AdditionController : Controller
    {
        private double current;

        public AdditionController()
        {
            current = 0;
        }

        //// GET: Addition
        //public ActionResult Index()
        //{
        //    ViewBag.Total = this.current;

        //    return View();
        //}

        public ActionResult Index([Bind(Include = "Number,Name")]Addition addition)
        {
            if(addition != null && !string.IsNullOrEmpty(addition.Name))
            {
                var total = Helper.Total + addition.Number;
                Helper.Total = total;
                Helper.History.Add(
                    new History
                    {
                        Name = addition.Name,
                        Number = addition.Number,
                        TotalThen = total
                    });
            }
            ViewBag.Total = Helper.Total;
            ViewBag.Entries = Helper.History;
            return View();
        }
    }

    
}

WebApplication2/Controllers/CombinedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class CombinedController : Controller
    {
        // GET: Combined
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";

            return View();
        }
    }
}

WebApplication2/Controllers/MovementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using WebApplication2.ViewModel.Movement;
using Newtonsoft.Json.Linq;

namespace WebApplication2.Controllers
{
    public class MovementController : Controller
    {
        private static string cookieKey = "Username";

        // GET: Positions
        public ActionResult Index()
        {
            HttpCookie myCookie = Request.Cookies[cookieKey];

            if(myCookie != null)
            {
                //ViewBag.UserId = myCookie.Value;
                return View(new UserIdViewModel { Id = int.Parse(myCookie.Value) });
            }
            else
            {
                return RedirectToAction("Create");
            }

        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(NewUserViewModel user)
        {
            using (var client = new HttpClient())
            {
                // In production this would be stored in a config file. So we could easily use different databases depending on inviroment.
                var uri = new Uri(Request.Url.Scheme + "://" + Request.Url.Authority + Request.ApplicationPath.TrimEnd('/') + "/api/");
                client.BaseAddress = uri;

                var responseTask = client.PostAsJsonAsync<NewUserViewModel>("user", user);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var read = result.Content.ReadAsAsync<int>();
                    read.Wait();
                    var id = read.Result;
                    
                    HttpCookie myCookie = new HttpCookie(cookieKey);
                    myCookie.Value = id.ToString();

                    myCookie.Expires = DateTime.Now.AddYears(50);

                    Response.Cookies.Add(myCookie);

                    return RedirectToAction("Index");
                }
                else
                {
                    return View("Error");
                }
            }
        }
    }
}

WebApplication2/Views/Home/Index.cshtml
<div class="content-wrapper" style="float: left;">
    @Html.ActionLink("Question 1", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" }) <br />
    @Html.ActionLink("Question 2", "Index", "Addition", new { area = "" }, new { @class = "navbar-brand" }) <br />
    @Html.ActionLink("Question 3", "Index", "Movement", new { area = "" }, new { @class = "navbar-brand" }) <br />
    @Html.ActionLink("Question 4", "Foo", "Bar", new { area = "" }, new { @class = "navbar-brand" }) <br />
    @Html.ActionLink("Question 5", "Index", "NextPrime", new { area = "" }, new { @class = "navbar-brand" }) <br />
    @Html.ActionLink("Question 6", "Index", "Adblock", new { area = "" }, new { @class = "navbar-brand" }) <br />
    @Html.ActionLink("Question 7", "Index", "Parallax", new { area = "" }, new { @class = "navbar-brand" }) <br />
    @Html.ActionLink("Question 8", "Index", "ThreeDimensions", new { area = "" }, new { @class = "navbar-brand" })
    @Html.ActionLink("v2", "VersionTwo", "ThreeDimensions", new { area = "" }, new { @class = "navbar-brand" }) <br />
    @Html.ActionLink("Question 9", "Index", "Combined", new { area = "" }, new { @class = "navbar-brand" }) <br />
</div>