WebApplication2/Controllers/AdblockController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class AdblockController : Controller
    {
        // GET: Adblock
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication2/Controllers/AdditionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class AdditionController : Controller
    {
        private double current;

        public AdditionController()
        {
            current = 0;
        }

        //// GET: Addition
        //public ActionResult Index()
        //{
        //    ViewBag.Total = this.current;

        //    return View();
        //}

        public ActionResult Index([Bind(Include = "Number,Name")]Addition addition)
        {
            if(addition != null && !string.IsNullOrEmpty(addition.Name))
            {
                var total = Helper.Total + addition.Number;
                Helper.Total = total;
                Helper.History.Add(
                    new History
                    {
                        Name = addition.Name,
                        Number = addition.Number,
                        TotalThen = total
                    });
            }
            ViewBag.Total = Helper.Total;
            ViewBag.Entries = Helper.History;
            return View();
        }
    }

    
}

WebApplication2/Controllers/CombinedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class CombinedController : Controller
    {
        // GET: Combined
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication2/Controllers/NextPrimeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class NextPrimeController : Controller
    {
        // GET: NextPrime
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication2/Views/Combined/Index.cshtml
@{
    ViewBag.Title = "Combined";
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Parallax Effect</title>
    <link rel="stylesheet" href="~/Content/style.css">
</head>
<body>
    <div class="rellax parallax-bg"></div>
    <div class="hero-image" data-rellax-speed="2"></div>
    <div class="rellax parallax-el" data-rellax-speed="5"></div>
    <div class="rellax text" data-rellax-speed="10"></div>
    <div class="rellax clouds" data-rellax-speed="8"></div>
    <div class="whitespace"></div>
    <div class="content">
        <h1>Combined</h1>
        <p>
            @Html.Action("Index", "NextPrime", new { })
            @Html.Action("Index", "Adblock", new { })
            @Html.Action("Index", "Addition", new { })
        </p>
    </div>
    <script src="~/Scripts/rellax.min.js"></script>
    <script type="text/javascript">
        var rellax = new Rellax('.rellax');
    </script>
</body>
</html>